package com.senlinjun.nek0

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.nio.charset.StandardCharsets
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Small Keystore-backed secret store for the personal fork.
 *
 * Ciphertexts live in a private SharedPreferences file, while the AES key is
 * non-exportable and generated by Android Keystore. Each value receives a new
 * random GCM IV and is authenticated with its logical storage key as AAD.
 *
 * User authentication is intentionally not required: the app needs to restore
 * its TeamSpeak identity while its foreground service is active. Device lock
 * and app sandbox protections still apply.
 */
class SecureStorage(context: Context) {
    private val prefs = context.applicationContext.getSharedPreferences(
        PREFS_NAME,
        Context.MODE_PRIVATE,
    )
    private val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
    private val filesRoot = context.applicationContext.filesDir

    @Synchronized
    fun put(key: String, value: String) {
        require(key.isNotBlank()) { "Secure storage key must not be blank" }
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateSecretKey())
        cipher.updateAAD(key.toByteArray(StandardCharsets.UTF_8))
        val ciphertext = cipher.doFinal(value.toByteArray(StandardCharsets.UTF_8))
        val encoded = Base64.encodeToString(cipher.iv, Base64.NO_WRAP) + "." +
            Base64.encodeToString(ciphertext, Base64.NO_WRAP)
        check(prefs.edit().putString(key, encoded).commit()) {
            "Failed to persist encrypted value"
        }
    }

    @Synchronized
    fun get(key: String): String? {
        require(key.isNotBlank()) { "Secure storage key must not be blank" }
        val encoded = prefs.getString(key, null) ?: return null
        val separator = encoded.indexOf('.')
        require(separator > 0 && separator < encoded.lastIndex) {
            "Invalid encrypted value format"
        }
        val iv = Base64.decode(encoded.substring(0, separator), Base64.NO_WRAP)
        val ciphertext = Base64.decode(encoded.substring(separator + 1), Base64.NO_WRAP)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            getOrCreateSecretKey(),
            GCMParameterSpec(GCM_TAG_BITS, iv),
        )
        cipher.updateAAD(key.toByteArray(StandardCharsets.UTF_8))
        return String(cipher.doFinal(ciphertext), StandardCharsets.UTF_8)
    }

    @Synchronized
    fun delete(key: String): Boolean {
        require(key.isNotBlank()) { "Secure storage key must not be blank" }
        return prefs.edit().remove(key).commit()
    }

    /**
     * Writes [value] encrypted into an app-private file named [name].
     *
     * SharedPreferences is the wrong home for a chat history: it is loaded
     * wholesale into memory and rewritten on every change. Files use the same
     * Keystore key and the same AAD discipline (the file name authenticates
     * the ciphertext, so a renamed file cannot be decrypted).
     */
    @Synchronized
    fun writeFile(name: String, value: String) {
        require(isSafeName(name)) { "Invalid secure file name" }
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateSecretKey())
        cipher.updateAAD(name.toByteArray(StandardCharsets.UTF_8))
        val ciphertext = cipher.doFinal(value.toByteArray(StandardCharsets.UTF_8))
        val target = java.io.File(secureDir(), name)
        // Write to a temporary file first: a process kill mid-write must not
        // leave an undecryptable history behind.
        val temporary = java.io.File(secureDir(), "$name.tmp")
        temporary.writeBytes(cipher.iv + ciphertext)
        check(temporary.renameTo(target)) { "Failed to persist encrypted file" }
    }

    /** Reads a file written by [writeFile]; null when absent or unreadable. */
    @Synchronized
    fun readFile(name: String): String? {
        require(isSafeName(name)) { "Invalid secure file name" }
        val file = java.io.File(secureDir(), name)
        if (!file.exists()) return null
        return try {
            val raw = file.readBytes()
            if (raw.size <= GCM_IV_BYTES) return null
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                getOrCreateSecretKey(),
                GCMParameterSpec(GCM_TAG_BITS, raw, 0, GCM_IV_BYTES),
            )
            cipher.updateAAD(name.toByteArray(StandardCharsets.UTF_8))
            String(
                cipher.doFinal(raw, GCM_IV_BYTES, raw.size - GCM_IV_BYTES),
                StandardCharsets.UTF_8,
            )
        } catch (_: Exception) {
            // Tampered, truncated or encrypted with a key that no longer
            // exists (app data restored on another device): treat as absent.
            file.delete()
            null
        }
    }

    @Synchronized
    fun deleteFile(name: String): Boolean {
        require(isSafeName(name)) { "Invalid secure file name" }
        val file = java.io.File(secureDir(), name)
        return !file.exists() || file.delete()
    }

    /** Removes every secure file. Used by "erase identity and secrets". */
    @Synchronized
    fun deleteAllFiles(): Int {
        var removed = 0
        secureDir().listFiles()?.forEach { if (it.delete()) removed++ }
        return removed
    }

    private fun secureDir(): java.io.File {
        val dir = java.io.File(filesRoot, SECURE_DIR)
        if (!dir.exists()) dir.mkdirs()
        return dir
    }

    /** Names are opaque handles chosen by Dart; never accept a path. */
    private fun isSafeName(name: String): Boolean =
        name.isNotBlank() &&
            name.length <= 128 &&
            name.all { it.isLetterOrDigit() || it == '_' || it == '-' || it == '.' } &&
            !name.contains("..")

    private fun getOrCreateSecretKey(): SecretKey {
        (keyStore.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        val generator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            ANDROID_KEYSTORE,
        )
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setRandomizedEncryptionRequired(true)
                .setUserAuthenticationRequired(false)
                .build(),
        )
        return generator.generateKey()
    }

    companion object {
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val KEY_ALIAS = "nek0.personal.secure_storage.v1"
        private const val PREFS_NAME = "nek0_secure_values_v1"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_TAG_BITS = 128
        private const val GCM_IV_BYTES = 12
        private const val SECURE_DIR = "nek0_secure_v1"
    }
}
